<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Evenement__CLASSMETADATA__' => 0,
'App__Entity__Alert__CLASSMETADATA__' => 1,
'App__Entity__Consultation__CLASSMETADATA__' => 2,
'App__Entity__Dogs__CLASSMETADATA__' => 3,
'App__Entity__Donation__CLASSMETADATA__' => 4,
'App__Entity__Categorie__CLASSMETADATA__' => 5,
'App__Entity__Commande__CLASSMETADATA__' => 6,
'App__Entity__LigneCommande__CLASSMETADATA__' => 7,
'App__Entity__Produit__CLASSMETADATA__' => 8,
'App__Entity__Guest__CLASSMETADATA__' => 9,
'App__Entity__ObservationStation__CLASSMETADATA__' => 10,
'App__Entity__Participation__CLASSMETADATA__' => 11,
'App__Entity__Suivi__CLASSMETADATA__' => 12,
'App__Entity__User__CLASSMETADATA__' => 13,
'App__Entity__Ziptag__CLASSMETADATA__' => 14,
'App__Entity__ZiptagInfo__CLASSMETADATA__' => 15,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Evenement',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\EvenementRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'titre' => $o[2],
                    'description' => $o[3],
                    'dateDebut' => $o[4],
                    'dateFin' => $o[5],
                    'lieu' => $o[6],
                    'ville' => $o[7],
                    'capaciteMax' => $o[8],
                    'type' => $o[9],
                    'statut' => $o[10],
                    'image' => $o[11],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'titre' => 'titre',
                    'description' => 'description',
                    'date_debut' => 'dateDebut',
                    'date_fin' => 'dateFin',
                    'lieu' => 'lieu',
                    'ville' => 'ville',
                    'capacite_max' => 'capaciteMax',
                    'type' => 'type',
                    'statut' => 'statut',
                    'image' => 'image',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'titre' => 'titre',
                    'description' => 'description',
                    'dateDebut' => 'date_debut',
                    'dateFin' => 'date_fin',
                    'lieu' => 'lieu',
                    'ville' => 'ville',
                    'capaciteMax' => 'capacite_max',
                    'type' => 'type',
                    'statut' => 'statut',
                    'image' => 'image',
                ],
            ],
            'table' => [
                [
                    'name' => 'evenement',
                ],
            ],
            'associationMappings' => [
                [
                    'participations' => $o[12],
                    'guests' => $o[13],
                ],
            ],
            'idGenerator' => [
                $o[14],
            ],
            'name' => [
                'App\\Entity\\Evenement',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'datetime',
                'datetime',
                'string',
                'string',
                'integer',
                'string',
                'string',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'titre',
                'description',
                'dateDebut',
                'dateFin',
                'lieu',
                'ville',
                'capaciteMax',
                'type',
                'statut',
                'image',
            ],
            'columnName' => [
                1 => 'id',
                'titre',
                'description',
                'date_debut',
                'date_fin',
                'lieu',
                'ville',
                'capacite_max',
                'type',
                'statut',
                'image',
            ],
            'length' => [
                2 => 255,
                6 => 255,
                100,
                9 => 50,
                50,
                255,
            ],
            'nullable' => [
                3 => true,
                5 => true,
                8 => true,
                11 => true,
            ],
            'cascade' => [
                12 => [
                    'remove',
                ],
                [
                    'remove',
                ],
            ],
            'fetch' => [
                12 => 2,
                2,
            ],
            'orphanRemoval' => [
                12 => true,
                true,
            ],
            'sourceEntity' => [
                12 => 'App\\Entity\\Evenement',
                'App\\Entity\\Evenement',
            ],
            'mappedBy' => [
                12 => 'evenement',
                'evenement',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                12 => 'participations',
                'guests',
            ],
            'targetEntity' => [
                12 => 'App\\Entity\\Participation',
                'App\\Entity\\Guest',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Alert',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\AlertRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'type' => $o[2],
                    'message' => $o[3],
                    'prioritee' => $o[4],
                    'statut' => $o[5],
                    'date' => $o[6],
                    'userId' => $o[7],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'type' => 'type',
                    'message' => 'message',
                    'prioritee' => 'prioritee',
                    'statut' => 'statut',
                    'date' => 'date',
                    'user_id' => 'userId',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'type' => 'type',
                    'message' => 'message',
                    'prioritee' => 'prioritee',
                    'statut' => 'statut',
                    'date' => 'date',
                    'userId' => 'user_id',
                ],
            ],
            'table' => [
                [
                    'name' => 'alert',
                ],
            ],
            'associationMappings' => [
                [
                    'station' => $o[8],
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\Alert',
                9 => 'station_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'integer',
                'string',
                'datetime',
                'integer',
            ],
            'fieldName' => [
                1 => 'id',
                'type',
                'message',
                'prioritee',
                'statut',
                'date',
                'userId',
            ],
            'columnName' => [
                1 => 'id',
                'type',
                'message',
                'prioritee',
                'statut',
                'date',
                'user_id',
            ],
            'length' => [
                2 => 50,
                5 => 50,
            ],
            'nullable' => [
                7 => true,
                9 => false,
            ],
            'fetch' => [
                8 => 2,
            ],
            'sourceEntity' => [
                8 => 'App\\Entity\\Alert',
            ],
            'inversedBy' => [
                8 => 'alerts',
            ],
            'sourceToTargetKeyColumns' => [
                8 => [
                    'station_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                8 => [
                    'id' => 'station_id',
                ],
            ],
            'joinColumns' => [
                8 => [
                    $o[9],
                ],
            ],
            'joinColumnFieldNames' => [
                8 => [
                    'station_id' => 'station_id',
                ],
            ],
            'deferrable' => [
                9 => false,
            ],
            'unique' => [
                9 => false,
            ],
            'referencedColumnName' => [
                9 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                8 => 'station',
            ],
            'targetEntity' => [
                8 => 'App\\Entity\\ObservationStation',
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Consultation',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ConsultationRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'date' => $o[2],
                    'type' => $o[3],
                    'diagnostic' => $o[4],
                    'traitement' => $o[5],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'date' => 'date',
                    'type' => 'type',
                    'diagnostic' => 'diagnostic',
                    'traitement' => 'traitement',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'date' => 'date',
                    'type' => 'type',
                    'diagnostic' => 'diagnostic',
                    'traitement' => 'traitement',
                ],
            ],
            'table' => [
                [
                    'name' => 'consultation',
                ],
            ],
            'associationMappings' => [
                [
                    'user' => $o[6],
                    'chien' => $o[8],
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\Consultation',
                7 => 'user_id',
                9 => 'chien_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'datetime_immutable',
                'string',
                'text',
                'text',
            ],
            'fieldName' => [
                1 => 'id',
                'date',
                'type',
                'diagnostic',
                'traitement',
            ],
            'columnName' => [
                1 => 'id',
                'date',
                'type',
                'diagnostic',
                'traitement',
            ],
            'length' => [
                3 => 50,
            ],
            'nullable' => [
                5 => true,
                7 => false,
                9 => false,
            ],
            'fetch' => [
                6 => 2,
                8 => 2,
            ],
            'sourceEntity' => [
                6 => 'App\\Entity\\Consultation',
                8 => 'App\\Entity\\Consultation',
            ],
            'inversedBy' => [
                6 => 'consultations',
                8 => 'consultations',
            ],
            'sourceToTargetKeyColumns' => [
                6 => [
                    'user_id' => 'id',
                ],
                8 => [
                    'chien_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                6 => [
                    'id' => 'user_id',
                ],
                8 => [
                    'id' => 'chien_id',
                ],
            ],
            'joinColumns' => [
                6 => [
                    $o[7],
                ],
                8 => [
                    $o[9],
                ],
            ],
            'joinColumnFieldNames' => [
                6 => [
                    'user_id' => 'user_id',
                ],
                8 => [
                    'chien_id' => 'chien_id',
                ],
            ],
            'deferrable' => [
                7 => false,
                9 => false,
            ],
            'unique' => [
                7 => false,
                9 => false,
            ],
            'referencedColumnName' => [
                7 => 'id',
                9 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                6 => 'user',
                8 => 'chien',
            ],
            'targetEntity' => [
                6 => 'App\\Entity\\User',
                8 => 'App\\Entity\\Dogs',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToOneInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToOneInverseSideMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Dogs',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\DogsRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'name' => $o[2],
                    'age' => $o[3],
                    'breed' => $o[4],
                    'gender' => $o[5],
                    'size' => $o[6],
                    'weight' => $o[7],
                    'vaccinated' => $o[8],
                    'friendly_with_kids' => $o[9],
                    'friendly_with_dogs' => $o[10],
                    'friendly_with_cats' => $o[11],
                    'health_status' => $o[12],
                    'adoption_status' => $o[13],
                    'arrival_date' => $o[14],
                    'image' => $o[15],
                    'description' => $o[16],
                    'microchip_number' => $o[17],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'age' => 'age',
                    'breed' => 'breed',
                    'gender' => 'gender',
                    'size' => 'size',
                    'weight' => 'weight',
                    'vaccinated' => 'vaccinated',
                    'friendly_with_kids' => 'friendly_with_kids',
                    'friendly_with_dogs' => 'friendly_with_dogs',
                    'friendly_with_cats' => 'friendly_with_cats',
                    'health_status' => 'health_status',
                    'adoption_status' => 'adoption_status',
                    'arrival_date' => 'arrival_date',
                    'image' => 'image',
                    'description' => 'description',
                    'microchip_number' => 'microchip_number',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'age' => 'age',
                    'breed' => 'breed',
                    'gender' => 'gender',
                    'size' => 'size',
                    'weight' => 'weight',
                    'vaccinated' => 'vaccinated',
                    'friendly_with_kids' => 'friendly_with_kids',
                    'friendly_with_dogs' => 'friendly_with_dogs',
                    'friendly_with_cats' => 'friendly_with_cats',
                    'health_status' => 'health_status',
                    'adoption_status' => 'adoption_status',
                    'arrival_date' => 'arrival_date',
                    'image' => 'image',
                    'description' => 'description',
                    'microchip_number' => 'microchip_number',
                ],
            ],
            'table' => [
                [
                    'name' => 'dogs',
                ],
            ],
            'associationMappings' => [
                [
                    'ziptag' => $o[18],
                    'user' => $o[19],
                ],
            ],
            'idGenerator' => [
                $o[21],
            ],
            'name' => [
                'App\\Entity\\Dogs',
                20 => 'user_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'integer',
                'string',
                'string',
                'string',
                'float',
                'boolean',
                'boolean',
                'boolean',
                'boolean',
                'string',
                'string',
                'datetime',
                'text',
                'text',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'name',
                'age',
                'breed',
                'gender',
                'size',
                'weight',
                'vaccinated',
                'friendly_with_kids',
                'friendly_with_dogs',
                'friendly_with_cats',
                'health_status',
                'adoption_status',
                'arrival_date',
                'image',
                'description',
                'microchip_number',
            ],
            'columnName' => [
                1 => 'id',
                'name',
                'age',
                'breed',
                'gender',
                'size',
                'weight',
                'vaccinated',
                'friendly_with_kids',
                'friendly_with_dogs',
                'friendly_with_cats',
                'health_status',
                'adoption_status',
                'arrival_date',
                'image',
                'description',
                'microchip_number',
            ],
            'length' => [
                2 => 255,
                4 => 255,
                255,
                255,
                12 => 255,
                255,
                17 => 255,
            ],
            'nullable' => [
                16 => true,
                true,
                20 => true,
            ],
            'cascade' => [
                18 => [
                    'persist',
                ],
            ],
            'fetch' => [
                18 => 2,
                2,
            ],
            'sourceEntity' => [
                18 => 'App\\Entity\\Dogs',
                'App\\Entity\\Dogs',
            ],
            'mappedBy' => [
                18 => 'dog',
            ],
            'inversedBy' => [
                19 => 'dogs',
            ],
            'sourceToTargetKeyColumns' => [
                19 => [
                    'user_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                19 => [
                    'id' => 'user_id',
                ],
            ],
            'joinColumns' => [
                19 => [
                    $o[20],
                ],
            ],
            'joinColumnFieldNames' => [
                19 => [
                    'user_id' => 'user_id',
                ],
            ],
            'deferrable' => [
                20 => false,
            ],
            'unique' => [
                20 => false,
            ],
            'referencedColumnName' => [
                20 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                18 => 'ziptag',
                'user',
            ],
            'targetEntity' => [
                18 => 'App\\Entity\\Ziptag',
                'App\\Entity\\User',
            ],
        ],
    ],
    $o[0],
    []
); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Donation',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\DonationRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'montant' => $o[2],
                    'date' => $o[3],
                    'donateur' => $o[4],
                    'email' => $o[5],
                    'reference' => $o[6],
                    'statut' => $o[7],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'montant' => 'montant',
                    'date' => 'date',
                    'donateur' => 'donateur',
                    'email' => 'email',
                    'reference' => 'reference',
                    'statut' => 'statut',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'montant' => 'montant',
                    'date' => 'date',
                    'donateur' => 'donateur',
                    'email' => 'email',
                    'reference' => 'reference',
                    'statut' => 'statut',
                ],
            ],
            'table' => [
                [
                    'name' => 'donation',
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\Donation',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'decimal',
                'date',
                'string',
                'string',
                'string',
                'boolean',
            ],
            'fieldName' => [
                1 => 'id',
                'montant',
                'date',
                'donateur',
                'email',
                'reference',
                'statut',
            ],
            'columnName' => [
                1 => 'id',
                'montant',
                'date',
                'donateur',
                'email',
                'reference',
                'statut',
            ],
            'precision' => [
                2 => 10,
            ],
            'scale' => [
                2 => 2,
            ],
            'length' => [
                4 => 255,
                255,
                100,
            ],
            'nullable' => [
                4 => true,
                true,
                true,
            ],
        ],
    ],
    $o[0],
    []
); } },
5 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Categorie',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\CategorieRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                ],
            ],
            'table' => [
                [
                    'name' => 'categorie',
                ],
            ],
            'associationMappings' => [
                [
                    'produits' => $o[3],
                ],
            ],
            'idGenerator' => [
                $o[4],
            ],
            'name' => [
                'App\\Entity\\Categorie',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'nom',
            ],
            'columnName' => [
                1 => 'id',
                'nom',
            ],
            'length' => [
                2 => 255,
            ],
            'fetch' => [
                3 => 2,
            ],
            'sourceEntity' => [
                3 => 'App\\Entity\\Categorie',
            ],
            'mappedBy' => [
                3 => 'categorie',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                3 => 'produits',
            ],
            'targetEntity' => [
                3 => 'App\\Entity\\Produit',
            ],
        ],
    ],
    $o[0],
    []
); } },
6 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Commande',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\CommandeRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'date' => $o[2],
                    'total' => $o[3],
                    'statut' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'date' => 'date',
                    'total' => 'total',
                    'statut' => 'statut',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'date' => 'date',
                    'total' => 'total',
                    'statut' => 'statut',
                ],
            ],
            'table' => [
                [
                    'name' => 'commande',
                ],
            ],
            'idGenerator' => [
                $o[5],
            ],
            'name' => [
                'App\\Entity\\Commande',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'date',
                'float',
                'boolean',
            ],
            'fieldName' => [
                1 => 'id',
                'date',
                'total',
                'statut',
            ],
            'columnName' => [
                1 => 'id',
                'date',
                'total',
                'statut',
            ],
        ],
    ],
    $o[0],
    []
); } },
7 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\LigneCommande',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\LigneCommandeRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'quantite' => $o[2],
                    'prixUnitaire' => $o[3],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'quantite' => 'quantite',
                    'prix_unitaire' => 'prixUnitaire',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'quantite' => 'quantite',
                    'prixUnitaire' => 'prix_unitaire',
                ],
            ],
            'table' => [
                [
                    'name' => 'ligne_commande',
                ],
            ],
            'associationMappings' => [
                [
                    'produit' => $o[4],
                    'commande' => $o[6],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\LigneCommande',
                5 => 'produit_id',
                7 => 'commande_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'integer',
                'decimal',
            ],
            'fieldName' => [
                1 => 'id',
                'quantite',
                'prixUnitaire',
            ],
            'columnName' => [
                1 => 'id',
                'quantite',
                'prix_unitaire',
            ],
            'precision' => [
                3 => 10,
            ],
            'scale' => [
                3 => 2,
            ],
            'fetch' => [
                4 => 2,
                6 => 2,
            ],
            'sourceEntity' => [
                4 => 'App\\Entity\\LigneCommande',
                6 => 'App\\Entity\\LigneCommande',
            ],
            'inversedBy' => [
                4 => 'ligneCommandes',
                6 => 'ligneCommandes',
            ],
            'sourceToTargetKeyColumns' => [
                4 => [
                    'produit_id' => 'id',
                ],
                6 => [
                    'commande_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                4 => [
                    'id' => 'produit_id',
                ],
                6 => [
                    'id' => 'commande_id',
                ],
            ],
            'joinColumns' => [
                4 => [
                    $o[5],
                ],
                6 => [
                    $o[7],
                ],
            ],
            'joinColumnFieldNames' => [
                4 => [
                    'produit_id' => 'produit_id',
                ],
                6 => [
                    'commande_id' => 'commande_id',
                ],
            ],
            'deferrable' => [
                5 => false,
                7 => false,
            ],
            'unique' => [
                5 => false,
                7 => false,
            ],
            'nullable' => [
                5 => false,
                7 => false,
            ],
            'referencedColumnName' => [
                5 => 'id',
                7 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                4 => 'produit',
                6 => 'commande',
            ],
            'targetEntity' => [
                4 => 'App\\Entity\\Produit',
                6 => 'App\\Entity\\Commande',
            ],
        ],
    ],
    $o[0],
    []
); } },
8 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Produit',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ProduitRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                    'prix' => $o[3],
                    'image' => $o[4],
                    'quantite' => $o[5],
                    'seuilAlert' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'prix' => 'prix',
                    'image' => 'image',
                    'quantite' => 'quantite',
                    'seuil_alert' => 'seuilAlert',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'prix' => 'prix',
                    'image' => 'image',
                    'quantite' => 'quantite',
                    'seuilAlert' => 'seuil_alert',
                ],
            ],
            'table' => [
                [
                    'name' => 'produit',
                ],
            ],
            'associationMappings' => [
                [
                    'categorie' => $o[7],
                ],
            ],
            'idGenerator' => [
                $o[9],
            ],
            'name' => [
                'App\\Entity\\Produit',
                8 => 'categorie',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'float',
                'string',
                'integer',
                'integer',
            ],
            'fieldName' => [
                1 => 'id',
                'nom',
                'prix',
                'image',
                'quantite',
                'seuilAlert',
            ],
            'columnName' => [
                1 => 'id',
                'nom',
                'prix',
                'image',
                'quantite',
                'seuil_alert',
            ],
            'length' => [
                2 => 255,
                4 => 255,
            ],
            'fetch' => [
                7 => 2,
            ],
            'sourceEntity' => [
                7 => 'App\\Entity\\Produit',
            ],
            'sourceToTargetKeyColumns' => [
                7 => [
                    'categorie' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                7 => [
                    'id' => 'categorie',
                ],
            ],
            'joinColumns' => [
                7 => [
                    $o[8],
                ],
            ],
            'joinColumnFieldNames' => [
                7 => [
                    'categorie' => 'categorie',
                ],
            ],
            'deferrable' => [
                8 => false,
            ],
            'unique' => [
                8 => false,
            ],
            'nullable' => [
                8 => false,
            ],
            'referencedColumnName' => [
                8 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                7 => 'categorie',
            ],
            'targetEntity' => [
                7 => 'App\\Entity\\Categorie',
            ],
        ],
    ],
    $o[0],
    []
); } },
9 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Guest',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\GuestRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'prenom' => $o[2],
                    'nom' => $o[3],
                    'email' => $o[4],
                    'phone' => $o[5],
                    'organisation' => $o[6],
                    'bio' => $o[7],
                    'role' => $o[8],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'prenom' => 'prenom',
                    'nom' => 'nom',
                    'email' => 'email',
                    'phone' => 'phone',
                    'organisation' => 'organisation',
                    'bio' => 'bio',
                    'role' => 'role',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'prenom' => 'prenom',
                    'nom' => 'nom',
                    'email' => 'email',
                    'phone' => 'phone',
                    'organisation' => 'organisation',
                    'bio' => 'bio',
                    'role' => 'role',
                ],
            ],
            'table' => [
                [
                    'name' => 'guest',
                ],
            ],
            'associationMappings' => [
                [
                    'evenement' => $o[9],
                ],
            ],
            'idGenerator' => [
                $o[11],
            ],
            'name' => [
                'App\\Entity\\Guest',
                10 => 'evenement_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
                'string',
                'text',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'prenom',
                'nom',
                'email',
                'phone',
                'organisation',
                'bio',
                'role',
            ],
            'columnName' => [
                1 => 'id',
                'prenom',
                'nom',
                'email',
                'phone',
                'organisation',
                'bio',
                'role',
            ],
            'length' => [
                2 => 100,
                100,
                255,
                20,
                255,
                8 => 50,
            ],
            'nullable' => [
                5 => true,
                true,
                true,
                10 => true,
            ],
            'fetch' => [
                9 => 2,
            ],
            'sourceEntity' => [
                9 => 'App\\Entity\\Guest',
            ],
            'inversedBy' => [
                9 => 'guests',
            ],
            'sourceToTargetKeyColumns' => [
                9 => [
                    'evenement_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                9 => [
                    'id' => 'evenement_id',
                ],
            ],
            'joinColumns' => [
                9 => [
                    $o[10],
                ],
            ],
            'joinColumnFieldNames' => [
                9 => [
                    'evenement_id' => 'evenement_id',
                ],
            ],
            'referencedColumnName' => [
                10 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                9 => 'evenement',
            ],
            'targetEntity' => [
                9 => 'App\\Entity\\Evenement',
            ],
        ],
    ],
    $o[0],
    []
); } },
10 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\ObservationStation',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ObservationStationRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'code' => $o[2],
                    'zone' => $o[3],
                    'localisation' => $o[4],
                    'statut' => $o[5],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'code' => 'code',
                    'zone' => 'zone',
                    'localisation' => 'localisation',
                    'statut' => 'statut',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'code' => 'code',
                    'zone' => 'zone',
                    'localisation' => 'localisation',
                    'statut' => 'statut',
                ],
            ],
            'table' => [
                [
                    'name' => 'observation_station',
                    'uniqueConstraints' => [
                        'uniq_observation_station_code' => [
                            'columns' => [
                                'code',
                            ],
                        ],
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'alerts' => $o[6],
                ],
            ],
            'idGenerator' => [
                $o[7],
            ],
            'name' => [
                'App\\Entity\\ObservationStation',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'code',
                'zone',
                'localisation',
                'statut',
            ],
            'columnName' => [
                1 => 'id',
                'code',
                'zone',
                'localisation',
                'statut',
            ],
            'length' => [
                2 => 255,
                50,
                255,
                50,
            ],
            'cascade' => [
                6 => [
                    'remove',
                ],
            ],
            'fetch' => [
                6 => 2,
            ],
            'orphanRemoval' => [
                6 => true,
            ],
            'sourceEntity' => [
                6 => 'App\\Entity\\ObservationStation',
            ],
            'mappedBy' => [
                6 => 'station',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                6 => 'alerts',
            ],
            'targetEntity' => [
                6 => 'App\\Entity\\Alert',
            ],
        ],
    ],
    $o[0],
    []
); } },
11 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Participation',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ParticipationRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'dateParticipation' => $o[2],
                    'statut' => $o[3],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'date_participation' => 'dateParticipation',
                    'statut' => 'statut',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'dateParticipation' => 'date_participation',
                    'statut' => 'statut',
                ],
            ],
            'table' => [
                [
                    'name' => 'participation',
                ],
            ],
            'associationMappings' => [
                [
                    'user' => $o[4],
                    'evenement' => $o[6],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\Participation',
                5 => 'user_id',
                7 => 'evenement_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'datetime',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'dateParticipation',
                'statut',
            ],
            'columnName' => [
                1 => 'id',
                'date_participation',
                'statut',
            ],
            'length' => [
                3 => 50,
            ],
            'fetch' => [
                4 => 2,
                6 => 2,
            ],
            'sourceEntity' => [
                4 => 'App\\Entity\\Participation',
                6 => 'App\\Entity\\Participation',
            ],
            'inversedBy' => [
                4 => 'participations',
                6 => 'participations',
            ],
            'sourceToTargetKeyColumns' => [
                4 => [
                    'user_id' => 'id',
                ],
                6 => [
                    'evenement_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                4 => [
                    'id' => 'user_id',
                ],
                6 => [
                    'id' => 'evenement_id',
                ],
            ],
            'joinColumns' => [
                4 => [
                    $o[5],
                ],
                6 => [
                    $o[7],
                ],
            ],
            'joinColumnFieldNames' => [
                4 => [
                    'user_id' => 'user_id',
                ],
                6 => [
                    'evenement_id' => 'evenement_id',
                ],
            ],
            'nullable' => [
                5 => true,
                7 => true,
            ],
            'referencedColumnName' => [
                5 => 'id',
                7 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                4 => 'user',
                6 => 'evenement',
            ],
            'targetEntity' => [
                4 => 'App\\Entity\\User',
                6 => 'App\\Entity\\Evenement',
            ],
        ],
    ],
    $o[0],
    []
); } },
12 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Suivi',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\SuiviRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'etat' => $o[2],
                    'recommandation' => $o[3],
                    'type' => $o[4],
                    'prochaineVisite' => $o[5],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'etat' => 'etat',
                    'recommandation' => 'recommandation',
                    'type' => 'type',
                    'prochaine_visite' => 'prochaineVisite',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'etat' => 'etat',
                    'recommandation' => 'recommandation',
                    'type' => 'type',
                    'prochaineVisite' => 'prochaine_visite',
                ],
            ],
            'table' => [
                [
                    'name' => 'suivi',
                ],
            ],
            'associationMappings' => [
                [
                    'consultation' => $o[6],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\Suivi',
                7 => 'consultation_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'string',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'etat',
                'recommandation',
                'type',
                'prochaineVisite',
            ],
            'columnName' => [
                1 => 'id',
                'etat',
                'recommandation',
                'type',
                'prochaine_visite',
            ],
            'length' => [
                2 => 50,
                4 => 255,
            ],
            'fetch' => [
                6 => 2,
            ],
            'sourceEntity' => [
                6 => 'App\\Entity\\Suivi',
            ],
            'sourceToTargetKeyColumns' => [
                6 => [
                    'consultation_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                6 => [
                    'id' => 'consultation_id',
                ],
            ],
            'joinColumns' => [
                6 => [
                    $o[7],
                ],
            ],
            'joinColumnFieldNames' => [
                6 => [
                    'consultation_id' => 'consultation_id',
                ],
            ],
            'deferrable' => [
                7 => false,
            ],
            'unique' => [
                7 => false,
            ],
            'nullable' => [
                7 => false,
            ],
            'referencedColumnName' => [
                7 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                6 => 'consultation',
            ],
            'targetEntity' => [
                6 => 'App\\Entity\\Consultation',
            ],
        ],
    ],
    $o[0],
    []
); } },
13 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\User',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\UserRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                    'prenom' => $o[3],
                    'email' => $o[4],
                    'telephone' => $o[5],
                    'role' => $o[6],
                    'status' => $o[7],
                    'password' => $o[8],
                    'user_image' => $o[9],
                    'order_number' => $o[10],
                    'matricule' => $o[11],
                    'zone_affectee' => $o[12],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'email' => 'email',
                    'telephone' => 'telephone',
                    'role' => 'role',
                    'status' => 'status',
                    'password' => 'password',
                    'user_image' => 'user_image',
                    'order_number' => 'order_number',
                    'matricule' => 'matricule',
                    'zone_affectee' => 'zone_affectee',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'prenom' => 'prenom',
                    'email' => 'email',
                    'telephone' => 'telephone',
                    'role' => 'role',
                    'status' => 'status',
                    'password' => 'password',
                    'user_image' => 'user_image',
                    'order_number' => 'order_number',
                    'matricule' => 'matricule',
                    'zone_affectee' => 'zone_affectee',
                ],
            ],
            'table' => [
                [
                    'name' => 'user',
                ],
            ],
            'associationMappings' => [
                [
                    'participations' => $o[13],
                ],
            ],
            'idGenerator' => [
                $o[14],
            ],
            'name' => [
                'App\\Entity\\User',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'integer',
                'string',
                'string',
                'string',
                'string',
                'integer',
                'string',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'nom',
                'prenom',
                'email',
                'telephone',
                'role',
                'status',
                'password',
                'user_image',
                'order_number',
                'matricule',
                'zone_affectee',
            ],
            'columnName' => [
                1 => 'id',
                'nom',
                'prenom',
                'email',
                'telephone',
                'role',
                'status',
                'password',
                'user_image',
                'order_number',
                'matricule',
                'zone_affectee',
            ],
            'length' => [
                2 => 30,
                30,
                100,
                6 => 20,
                10,
                100,
                255,
                11 => 10,
                255,
            ],
            'nullable' => [
                10 => true,
                true,
                true,
            ],
            'cascade' => [
                13 => [
                    'remove',
                ],
            ],
            'fetch' => [
                13 => 2,
            ],
            'orphanRemoval' => [
                13 => true,
            ],
            'sourceEntity' => [
                13 => 'App\\Entity\\User',
            ],
            'mappedBy' => [
                13 => 'user',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                13 => 'participations',
            ],
            'targetEntity' => [
                13 => 'App\\Entity\\Participation',
            ],
        ],
    ],
    $o[0],
    []
); } },
14 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Ziptag',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ZiptagRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'serialNumber' => $o[2],
                    'firmwareVersion' => $o[3],
                    'model' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'serial_number' => 'serialNumber',
                    'firmware_version' => 'firmwareVersion',
                    'model' => 'model',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'serialNumber' => 'serial_number',
                    'firmwareVersion' => 'firmware_version',
                    'model' => 'model',
                ],
            ],
            'table' => [
                [
                    'name' => 'ziptages',
                ],
            ],
            'associationMappings' => [
                [
                    'dog' => $o[5],
                    'infos' => $o[7],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\Ziptag',
                6 => 'dog_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'serialNumber',
                'firmwareVersion',
                'model',
            ],
            'columnName' => [
                1 => 'id',
                'serial_number',
                'firmware_version',
                'model',
            ],
            'length' => [
                2 => 255,
                255,
                255,
            ],
            'unique' => [
                2 => true,
                6 => true,
            ],
            'cascade' => [
                5 => [
                    'persist',
                ],
                7 => [
                    'remove',
                ],
            ],
            'fetch' => [
                5 => 2,
                7 => 2,
            ],
            'sourceEntity' => [
                5 => 'App\\Entity\\Ziptag',
                7 => 'App\\Entity\\Ziptag',
            ],
            'inversedBy' => [
                5 => 'ziptag',
            ],
            'sourceToTargetKeyColumns' => [
                5 => [
                    'dog_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                5 => [
                    'id' => 'dog_id',
                ],
            ],
            'joinColumns' => [
                5 => [
                    $o[6],
                ],
            ],
            'joinColumnFieldNames' => [
                5 => [
                    'dog_id' => 'dog_id',
                ],
            ],
            'deferrable' => [
                6 => false,
            ],
            'nullable' => [
                6 => true,
            ],
            'referencedColumnName' => [
                6 => 'id',
            ],
            'orphanRemoval' => [
                7 => true,
            ],
            'mappedBy' => [
                7 => 'ziptag',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                5 => 'dog',
                7 => 'infos',
            ],
            'targetEntity' => [
                5 => 'App\\Entity\\Dogs',
                7 => 'App\\Entity\\ZiptagInfo',
            ],
        ],
    ],
    $o[0],
    []
); } },
15 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\ZiptagInfo',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ZiptagInfoRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'type' => $o[2],
                    'message' => $o[3],
                    'location' => $o[4],
                    'batteryLevel' => $o[5],
                    'heartRate' => $o[6],
                    'bodyTemperature' => $o[7],
                    'createdAt' => $o[8],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'type' => 'type',
                    'message' => 'message',
                    'location' => 'location',
                    'battery_level' => 'batteryLevel',
                    'heart_rate' => 'heartRate',
                    'body_temperature' => 'bodyTemperature',
                    'created_at' => 'createdAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'type' => 'type',
                    'message' => 'message',
                    'location' => 'location',
                    'batteryLevel' => 'battery_level',
                    'heartRate' => 'heart_rate',
                    'bodyTemperature' => 'body_temperature',
                    'createdAt' => 'created_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'ziptag_infos',
                ],
            ],
            'associationMappings' => [
                [
                    'ziptag' => $o[9],
                ],
            ],
            'idGenerator' => [
                $o[11],
            ],
            'name' => [
                'App\\Entity\\ZiptagInfo',
                10 => 'ziptage_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'float',
                'float',
                'float',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'type',
                'message',
                'location',
                'batteryLevel',
                'heartRate',
                'bodyTemperature',
                'createdAt',
            ],
            'columnName' => [
                1 => 'id',
                'type',
                'message',
                'location',
                'battery_level',
                'heart_rate',
                'body_temperature',
                'created_at',
            ],
            'length' => [
                2 => 255,
                255,
                255,
            ],
            'nullable' => [
                3 => true,
                true,
                true,
                true,
                true,
                10 => false,
            ],
            'fetch' => [
                9 => 2,
            ],
            'sourceEntity' => [
                9 => 'App\\Entity\\ZiptagInfo',
            ],
            'inversedBy' => [
                9 => 'infos',
            ],
            'sourceToTargetKeyColumns' => [
                9 => [
                    'ziptage_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                9 => [
                    'id' => 'ziptage_id',
                ],
            ],
            'joinColumns' => [
                9 => [
                    $o[10],
                ],
            ],
            'joinColumnFieldNames' => [
                9 => [
                    'ziptage_id' => 'ziptage_id',
                ],
            ],
            'deferrable' => [
                10 => false,
            ],
            'unique' => [
                10 => false,
            ],
            'referencedColumnName' => [
                10 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                9 => 'ziptag',
            ],
            'targetEntity' => [
                9 => 'App\\Entity\\Ziptag',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
