<?php

namespace ContainerOdjCx9K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..SahYEd.App\Entity\Guest' shared service.
     *
     * @return \App\Entity\Guest
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..SahYEd": it needs an instance of "App\\Entity\\Guest" but this type has been excluded in "config/services.yaml".');
    }
}
