<?php

namespace ContainerOdjCx9K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7Fv2XHF.App\Entity\Participation' shared service.
     *
     * @return \App\Entity\Participation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.7Fv2XHF": it needs an instance of "App\\Entity\\Participation" but this type has been excluded in "config/services.yaml".');
    }
}
