<?php

namespace ContainerEUeFEUx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PlbXKuPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.plbXKuP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'suivi' => ['privates', '.errored..service_locator.plbXKuP.App\\Entity\\Suivi', NULL, 'Cannot autowire service ".service_locator.plbXKuP": it needs an instance of "App\\Entity\\Suivi" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'suivi' => 'App\\Entity\\Suivi',
        ]);

        if (isset($container->privates['.service_locator.plbXKuP'])) {
            return $container->privates['.service_locator.plbXKuP'];
        }

        return $container->privates['.service_locator.plbXKuP'] = $instance;
    }
}
