<?php

namespace ContainerEUeFEUx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuiviService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.plbXKuP.App\Entity\Suivi' shared service.
     *
     * @return \App\Entity\Suivi
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.plbXKuP": it needs an instance of "App\\Entity\\Suivi" but this type has been excluded in "config/services.yaml".');
    }
}
