<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCKuSrlE\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCKuSrlE/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerCKuSrlE.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerCKuSrlE\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerCKuSrlE\App_KernelProdContainer([
    'container.build_hash' => 'CKuSrlE',
    'container.build_id' => '1299ee66',
    'container.build_time' => 1770669521,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCKuSrlE');
