<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'matricule' => [parent::class, 'matricule', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'order_number' => [parent::class, 'order_number', null, 16],
        "\0".parent::class."\0".'participations' => [parent::class, 'participations', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        "\0".parent::class."\0".'user_face' => [parent::class, 'user_face', null, 16],
        "\0".parent::class."\0".'user_image' => [parent::class, 'user_image', null, 16],
        "\0".parent::class."\0".'zone_affectee' => [parent::class, 'zone_affectee', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'matricule' => [parent::class, 'matricule', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'order_number' => [parent::class, 'order_number', null, 16],
        'participations' => [parent::class, 'participations', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
        'user_face' => [parent::class, 'user_face', null, 16],
        'user_image' => [parent::class, 'user_image', null, 16],
        'zone_affectee' => [parent::class, 'zone_affectee', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
