<?php

namespace ContainerRg5fO1A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P3X5T9UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p3X5T9U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p3X5T9U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dogsRepository' => ['privates', 'App\\Repository\\DogsRepository', 'getDogsRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'dogsRepository' => 'App\\Repository\\DogsRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
