<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZQK9e7IService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ZQK9e7I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ligne' => ['privates', '.errored..service_locator.ZQK9e7I.App\\Entity\\LigneCommande', NULL, 'Cannot autowire service ".service_locator.ZQK9e7I": it needs an instance of "App\\Entity\\LigneCommande" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'ligne' => 'App\\Entity\\LigneCommande',
        ]);

        if (isset($container->privates['.service_locator.ZQK9e7I'])) {
            return $container->privates['.service_locator.ZQK9e7I'];
        }

        return $container->privates['.service_locator.ZQK9e7I'] = $instance;
    }
}
