<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A9EJIICService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.a9EJIIC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a9EJIIC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'alertRepository' => ['privates', 'App\\Repository\\AlertRepository', 'getAlertRepositoryService', true],
        ], [
            'alertRepository' => 'App\\Repository\\AlertRepository',
        ]);
    }
}
