<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gs_6f9PService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Gs.6f9P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gs.6f9P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'alert' => ['privates', '.errored..service_locator.Gs.6f9P.App\\Entity\\Alert', NULL, 'Cannot autowire service ".service_locator.Gs.6f9P": it needs an instance of "App\\Entity\\Alert" but this type has been excluded in "config/services.yaml".'],
        ], [
            'alert' => 'App\\Entity\\Alert',
        ]);
    }
}
