<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SzQKkkFService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.SzQKkkF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'observationStation' => ['privates', '.errored..service_locator.SzQKkkF.App\\Entity\\ObservationStation', NULL, 'Cannot autowire service ".service_locator.SzQKkkF": it needs an instance of "App\\Entity\\ObservationStation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'observationStation' => 'App\\Entity\\ObservationStation',
        ]);

        if (isset($container->privates['.service_locator.SzQKkkF'])) {
            return $container->privates['.service_locator.SzQKkkF'];
        }

        return $container->privates['.service_locator.SzQKkkF'] = $instance;
    }
}
