<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ODI3nJ3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.oDI3nJ3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ziptagRepository' => ['privates', 'App\\Repository\\ZiptagRepository', 'getZiptagRepositoryService', true],
        ], [
            'entityManager' => '?',
            'ziptagRepository' => 'App\\Repository\\ZiptagRepository',
        ]);

        if (isset($container->privates['.service_locator.oDI3nJ3'])) {
            return $container->privates['.service_locator.oDI3nJ3'];
        }

        return $container->privates['.service_locator.oDI3nJ3'] = $instance;
    }
}
