<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DXuwMvlService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.DXuwMvl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DXuwMvl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'guest' => ['privates', '.errored..service_locator.DXuwMvl.App\\Entity\\Guest', NULL, 'Cannot autowire service ".service_locator.DXuwMvl": it needs an instance of "App\\Entity\\Guest" but this type has been excluded in "config/services.yaml".'],
        ], [
            'guest' => 'App\\Entity\\Guest',
        ]);
    }
}
