<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A4F0c8hService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.A4F0c8h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A4F0c8h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'normalizer' => ['privates', '.errored.u108s6J', NULL, 'Cannot determine controller argument for "App\\Controller\\ObservationStationController::searchStations()": the $normalizer argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Serializer\\NormaliZerInterface".'],
            'observationStationRepository' => ['privates', 'App\\Repository\\ObservationStationRepository', 'getObservationStationRepositoryService', true],
        ], [
            'normalizer' => '?',
            'observationStationRepository' => 'App\\Repository\\ObservationStationRepository',
        ]);
    }
}
