<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NNuPxAService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.n_NuPxA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'normalizer' => ['privates', 'serializer', 'getSerializerService', false],
            'ziptagRepository' => ['privates', 'App\\Repository\\ZiptagRepository', 'getZiptagRepositoryService', true],
        ], [
            'normalizer' => '?',
            'ziptagRepository' => 'App\\Repository\\ZiptagRepository',
        ]);

        if (isset($container->privates['.service_locator.n_NuPxA'])) {
            return $container->privates['.service_locator.n_NuPxA'];
        }

        return $container->privates['.service_locator.n_NuPxA'] = $instance;
    }
}
