<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CqzndDCService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.CqzndDC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CqzndDC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dog' => ['privates', '.errored..service_locator.CqzndDC.App\\Entity\\Dogs', NULL, 'Cannot autowire service ".service_locator.CqzndDC": it needs an instance of "App\\Entity\\Dogs" but this type has been excluded in "config/services.yaml".'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'dog' => 'App\\Entity\\Dogs',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
