<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BpR4VVZService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.BpR4VVZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'alert' => ['privates', '.errored..service_locator.BpR4VVZ.App\\Entity\\Alert', NULL, 'Cannot autowire service ".service_locator.BpR4VVZ": it needs an instance of "App\\Entity\\Alert" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'alert' => 'App\\Entity\\Alert',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.BpR4VVZ'])) {
            return $container->privates['.service_locator.BpR4VVZ'];
        }

        return $container->privates['.service_locator.BpR4VVZ'] = $instance;
    }
}
