<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rw6aBCmService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Rw6aBCm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dogsRepository' => ['privates', 'App\\Repository\\DogsRepository', 'getDogsRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ziptag' => ['privates', '.errored..service_locator.Rw6aBCm.App\\Entity\\Ziptag', NULL, 'Cannot autowire service ".service_locator.Rw6aBCm": it needs an instance of "App\\Entity\\Ziptag" but this type has been excluded in "config/services.yaml".'],
        ], [
            'dogsRepository' => 'App\\Repository\\DogsRepository',
            'entityManager' => '?',
            'ziptag' => 'App\\Entity\\Ziptag',
        ]);

        if (isset($container->privates['.service_locator.Rw6aBCm'])) {
            return $container->privates['.service_locator.Rw6aBCm'];
        }

        return $container->privates['.service_locator.Rw6aBCm'] = $instance;
    }
}
