<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fu0ikigService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.fu0ikig' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fu0ikig'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ligne' => ['privates', '.errored..service_locator.fu0ikig.App\\Entity\\LigneCommande', NULL, 'Cannot autowire service ".service_locator.fu0ikig": it needs an instance of "App\\Entity\\LigneCommande" but this type has been excluded in "config/services.yaml".'],
        ], [
            'ligne' => 'App\\Entity\\LigneCommande',
        ]);
    }
}
