<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4N6_USService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.4N6._US' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commande' => ['privates', '.errored..service_locator.4N6._US.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.4N6._US": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.4N6._US'])) {
            return $container->privates['.service_locator.4N6._US'];
        }

        return $container->privates['.service_locator.4N6._US'] = $instance;
    }
}
