<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_U108s6JService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored.u108s6J' shared service.
     *
     * @return \Symfony\Component\Serializer\NormaliZerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ObservationStationController::searchStations()": the $normalizer argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Serializer\\NormaliZerInterface".');
    }
}
