<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VhlSIeAService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.vhlSIeA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vhlSIeA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ziptag' => ['privates', '.errored..service_locator.vhlSIeA.App\\Entity\\Ziptag', NULL, 'Cannot autowire service ".service_locator.vhlSIeA": it needs an instance of "App\\Entity\\Ziptag" but this type has been excluded in "config/services.yaml".'],
        ], [
            'ziptag' => 'App\\Entity\\Ziptag',
        ]);
    }
}
