<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_50OOkX6Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.50OOkX6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'consultation' => ['privates', '.errored..service_locator.50OOkX6.App\\Entity\\Consultation', NULL, 'Cannot autowire service ".service_locator.50OOkX6": it needs an instance of "App\\Entity\\Consultation" but this type has been excluded in "config/services.yaml".'],
            'consultationRepository' => ['privates', 'App\\Repository\\ConsultationRepository', 'getConsultationRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'consultation' => 'App\\Entity\\Consultation',
            'consultationRepository' => 'App\\Repository\\ConsultationRepository',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.50OOkX6'])) {
            return $container->privates['.service_locator.50OOkX6'];
        }

        return $container->privates['.service_locator.50OOkX6'] = $instance;
    }
}
