<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LTXIpMService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator._lTXIpM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dogsRepository' => ['privates', 'App\\Repository\\DogsRepository', 'getDogsRepositoryService', true],
            'normalizer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'dogsRepository' => 'App\\Repository\\DogsRepository',
            'normalizer' => '?',
        ]);

        if (isset($container->privates['.service_locator._lTXIpM'])) {
            return $container->privates['.service_locator._lTXIpM'];
        }

        return $container->privates['.service_locator._lTXIpM'] = $instance;
    }
}
