<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rg4sZIService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.rg4sZ_i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dogsRepository' => ['privates', 'App\\Repository\\DogsRepository', 'getDogsRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dogsRepository' => 'App\\Repository\\DogsRepository',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.rg4sZ_i'])) {
            return $container->privates['.service_locator.rg4sZ_i'];
        }

        return $container->privates['.service_locator.rg4sZ_i'] = $instance;
    }
}
