<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7hG3BaService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator._7hG3Ba' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'participation' => ['privates', '.errored..service_locator._7hG3Ba.App\\Entity\\Participation', NULL, 'Cannot autowire service ".service_locator._7hG3Ba": it needs an instance of "App\\Entity\\Participation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'participation' => 'App\\Entity\\Participation',
        ]);

        if (isset($container->privates['.service_locator._7hG3Ba'])) {
            return $container->privates['.service_locator._7hG3Ba'];
        }

        return $container->privates['.service_locator._7hG3Ba'] = $instance;
    }
}
