<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qs1pVnJService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.qs1pVnJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qs1pVnJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dogsRepository' => ['privates', 'App\\Repository\\DogsRepository', 'getDogsRepositoryService', true],
        ], [
            'dogsRepository' => 'App\\Repository\\DogsRepository',
        ]);
    }
}
