<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UqDDRsGService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.uqDDRsG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cache' => ['services', 'cache.app', 'getCache_AppService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'cache' => '?',
            'logger' => '?',
            'mailer' => '?',
            'urlGenerator' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.uqDDRsG'])) {
            return $container->privates['.service_locator.uqDDRsG'];
        }

        return $container->privates['.service_locator.uqDDRsG'] = $instance;
    }
}
