<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UsqzJ0JService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.usqzJ0J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dog' => ['privates', '.errored..service_locator.usqzJ0J.App\\Entity\\Dogs', NULL, 'Cannot autowire service ".service_locator.usqzJ0J": it needs an instance of "App\\Entity\\Dogs" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dog' => 'App\\Entity\\Dogs',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.usqzJ0J'])) {
            return $container->privates['.service_locator.usqzJ0J'];
        }

        return $container->privates['.service_locator.usqzJ0J'] = $instance;
    }
}
