<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7Fv2XHFService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.7Fv2XHF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7Fv2XHF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'participation' => ['privates', '.errored..service_locator.7Fv2XHF.App\\Entity\\Participation', NULL, 'Cannot autowire service ".service_locator.7Fv2XHF": it needs an instance of "App\\Entity\\Participation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'participation' => 'App\\Entity\\Participation',
        ]);
    }
}
