<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlert2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Gs.6f9P.App\Entity\Alert' shared service.
     *
     * @return \App\Entity\Alert
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Gs.6f9P": it needs an instance of "App\\Entity\\Alert" but this type has been excluded in "config/services.yaml".');
    }
}
