<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminEventsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AdminEventsController' shared autowired service.
     *
     * @return \App\Controller\AdminEventsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AdminEventsController'] = $instance = new \App\Controller\AdminEventsController(($container->privates['validator'] ?? self::getValidatorService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\AdminEventsController', $container));

        return $instance;
    }
}
