<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.4N6._US.App\Entity\Commande' shared service.
     *
     * @return \App\Entity\Commande
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4N6._US": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".');
    }
}
