<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Eshop\CommandeController' shared autowired service.
     *
     * @return \App\Controller\Eshop\CommandeController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Eshop\\CommandeController'] = $instance = new \App\Controller\Eshop\CommandeController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Eshop\\CommandeController', $container));

        return $instance;
    }
}
