<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CommandeType' shared autowired service.
     *
     * @return \App\Form\CommandeType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CommandeType'] = new \App\Form\CommandeType();
    }
}
