<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Eshop\CategorieController' shared autowired service.
     *
     * @return \App\Controller\Eshop\CategorieController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Eshop\\CategorieController'] = $instance = new \App\Controller\Eshop\CategorieController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Eshop\\CategorieController', $container));

        return $instance;
    }
}
