<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDonationTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\DonationType' shared autowired service.
     *
     * @return \App\Form\DonationType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\DonationType'] = new \App\Form\DonationType();
    }
}
