<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDogsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DogsController' shared autowired service.
     *
     * @return \App\Controller\DogsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DogsController'] = $instance = new \App\Controller\DogsController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\DogsController', $container));

        return $instance;
    }
}
