<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDogsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\DogsRepository' shared autowired service.
     *
     * @return \App\Repository\DogsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DogsRepository'] = new \App\Repository\DogsRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
