<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDonationService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.86FluUf.App\Entity\Donation' shared service.
     *
     * @return \App\Entity\Donation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.86FluUf": it needs an instance of "App\\Entity\\Donation" but this type has been excluded in "config/services.yaml".');
    }
}
