<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDogs3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.WX1szdI.App\Entity\Dogs' shared service.
     *
     * @return \App\Entity\Dogs
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.WX1szdI": it needs an instance of "App\\Entity\\Dogs" but this type has been excluded in "config/services.yaml".');
    }
}
