<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuestRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\GuestRepository' shared autowired service.
     *
     * @return \App\Repository\GuestRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\GuestRepository'] = new \App\Repository\GuestRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
