<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLigneCommandeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\LigneCommandeRepository' shared autowired service.
     *
     * @return \App\Repository\LigneCommandeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LigneCommandeRepository'] = new \App\Repository\LigneCommandeRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
