<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLigneCommande2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.ZQK9e7I.App\Entity\LigneCommande' shared service.
     *
     * @return \App\Entity\LigneCommande
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ZQK9e7I": it needs an instance of "App\\Entity\\LigneCommande" but this type has been excluded in "config/services.yaml".');
    }
}
