<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\NotificationService' shared autowired service.
     *
     * @return \App\Service\NotificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\NotificationService'])) {
            return $container->privates['App\\Service\\NotificationService'];
        }

        $instance = new \App\Service\NotificationService(($container->privates['App\\Repository\\AlertRepository'] ?? $container->load('getAlertRepositoryService')), $a);

        if (isset($container->privates['App\\Service\\NotificationService'])) {
            return $container->privates['App\\Service\\NotificationService'];
        }

        return $container->privates['App\\Service\\NotificationService'] = $instance;
    }
}
