<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObservationStationService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.SzQKkkF.App\Entity\ObservationStation' shared service.
     *
     * @return \App\Entity\ObservationStation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SzQKkkF": it needs an instance of "App\\Entity\\ObservationStation" but this type has been excluded in "config/services.yaml".');
    }
}
