<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicEventControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PublicEventController' shared autowired service.
     *
     * @return \App\Controller\PublicEventController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PublicEventController'] = $instance = new \App\Controller\PublicEventController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PublicEventController', $container));

        return $instance;
    }
}
