<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipation2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator._7hG3Ba.App\Entity\Participation' shared service.
     *
     * @return \App\Entity\Participation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._7hG3Ba": it needs an instance of "App\\Entity\\Participation" but this type has been excluded in "config/services.yaml".');
    }
}
