<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ParticipationRepository' shared autowired service.
     *
     * @return \App\Repository\ParticipationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ParticipationRepository'] = new \App\Repository\ParticipationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
