<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignupTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\SignupType' shared autowired service.
     *
     * @return \App\Form\SignupType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SignupType'] = new \App\Form\SignupType();
    }
}
