<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSigninTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\SigninType' shared autowired service.
     *
     * @return \App\Form\SigninType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SigninType'] = new \App\Form\SigninType();
    }
}
