<?php

namespace ContainerCKuSrlE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZiptagService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Rw6aBCm.App\Entity\Ziptag' shared service.
     *
     * @return \App\Entity\Ziptag
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Rw6aBCm": it needs an instance of "App\\Entity\\Ziptag" but this type has been excluded in "config/services.yaml".');
    }
}
