<?php

namespace ContainerXs1qjG4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LRzV_GsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lRzV.gs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ConsultationController::delete' => ['privates', '.service_locator.dKSU_jY', 'get_ServiceLocator_DKSUJYService', true],
            'App\\Controller\\ConsultationController::edit' => ['privates', '.service_locator.dKSU_jY', 'get_ServiceLocator_DKSUJYService', true],
            'App\\Controller\\ConsultationController::index' => ['privates', '.service_locator.NpEkuJn', 'get_ServiceLocator_NpEkuJnService', true],
            'App\\Controller\\ConsultationController::new' => ['privates', '.service_locator.f9Tu_kp', 'get_ServiceLocator_F9TuKpService', true],
            'App\\Controller\\ConsultationController::search' => ['privates', '.service_locator.NpEkuJn', 'get_ServiceLocator_NpEkuJnService', true],
            'App\\Controller\\ConsultationController::sortByDate' => ['privates', '.service_locator.NpEkuJn', 'get_ServiceLocator_NpEkuJnService', true],
            'App\\Controller\\PageController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PageController::settings' => ['privates', '.service_locator.NjUBG3v', 'get_ServiceLocator_NjUBG3vService', true],
            'App\\Controller\\PageController::veterinarianPage' => ['privates', '.service_locator.p3X5T9U', 'get_ServiceLocator_P3X5T9UService', true],
            'App\\Controller\\SuiviController::aiAnalyze' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController::consultationDetail' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController::delete' => ['privates', '.service_locator.Fg93DDd', 'get_ServiceLocator_Fg93DDdService', true],
            'App\\Controller\\SuiviController::edit' => ['privates', '.service_locator.Fg93DDd', 'get_ServiceLocator_Fg93DDdService', true],
            'App\\Controller\\SuiviController::exportPdf' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController::filterByEmergency' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController::getOrganSymptoms' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController::index' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController::searchByEtat' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController::searchByType' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController::sortByDate' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ConsultationController:delete' => ['privates', '.service_locator.dKSU_jY', 'get_ServiceLocator_DKSUJYService', true],
            'App\\Controller\\ConsultationController:edit' => ['privates', '.service_locator.dKSU_jY', 'get_ServiceLocator_DKSUJYService', true],
            'App\\Controller\\ConsultationController:index' => ['privates', '.service_locator.NpEkuJn', 'get_ServiceLocator_NpEkuJnService', true],
            'App\\Controller\\ConsultationController:new' => ['privates', '.service_locator.f9Tu_kp', 'get_ServiceLocator_F9TuKpService', true],
            'App\\Controller\\ConsultationController:search' => ['privates', '.service_locator.NpEkuJn', 'get_ServiceLocator_NpEkuJnService', true],
            'App\\Controller\\ConsultationController:sortByDate' => ['privates', '.service_locator.NpEkuJn', 'get_ServiceLocator_NpEkuJnService', true],
            'App\\Controller\\PageController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PageController:settings' => ['privates', '.service_locator.NjUBG3v', 'get_ServiceLocator_NjUBG3vService', true],
            'App\\Controller\\PageController:veterinarianPage' => ['privates', '.service_locator.p3X5T9U', 'get_ServiceLocator_P3X5T9UService', true],
            'App\\Controller\\SuiviController:aiAnalyze' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController:consultationDetail' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController:delete' => ['privates', '.service_locator.Fg93DDd', 'get_ServiceLocator_Fg93DDdService', true],
            'App\\Controller\\SuiviController:edit' => ['privates', '.service_locator.Fg93DDd', 'get_ServiceLocator_Fg93DDdService', true],
            'App\\Controller\\SuiviController:exportPdf' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController:filterByEmergency' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController:getOrganSymptoms' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController:index' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController:searchByEtat' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController:searchByType' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'App\\Controller\\SuiviController:sortByDate' => ['privates', '.service_locator.uuML20f', 'get_ServiceLocator_UuML20fService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ConsultationController::delete' => '?',
            'App\\Controller\\ConsultationController::edit' => '?',
            'App\\Controller\\ConsultationController::index' => '?',
            'App\\Controller\\ConsultationController::new' => '?',
            'App\\Controller\\ConsultationController::search' => '?',
            'App\\Controller\\ConsultationController::sortByDate' => '?',
            'App\\Controller\\PageController::index' => '?',
            'App\\Controller\\PageController::settings' => '?',
            'App\\Controller\\PageController::veterinarianPage' => '?',
            'App\\Controller\\SuiviController::aiAnalyze' => '?',
            'App\\Controller\\SuiviController::consultationDetail' => '?',
            'App\\Controller\\SuiviController::delete' => '?',
            'App\\Controller\\SuiviController::edit' => '?',
            'App\\Controller\\SuiviController::exportPdf' => '?',
            'App\\Controller\\SuiviController::filterByEmergency' => '?',
            'App\\Controller\\SuiviController::getOrganSymptoms' => '?',
            'App\\Controller\\SuiviController::index' => '?',
            'App\\Controller\\SuiviController::searchByEtat' => '?',
            'App\\Controller\\SuiviController::searchByType' => '?',
            'App\\Controller\\SuiviController::sortByDate' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ConsultationController:delete' => '?',
            'App\\Controller\\ConsultationController:edit' => '?',
            'App\\Controller\\ConsultationController:index' => '?',
            'App\\Controller\\ConsultationController:new' => '?',
            'App\\Controller\\ConsultationController:search' => '?',
            'App\\Controller\\ConsultationController:sortByDate' => '?',
            'App\\Controller\\PageController:index' => '?',
            'App\\Controller\\PageController:settings' => '?',
            'App\\Controller\\PageController:veterinarianPage' => '?',
            'App\\Controller\\SuiviController:aiAnalyze' => '?',
            'App\\Controller\\SuiviController:consultationDetail' => '?',
            'App\\Controller\\SuiviController:delete' => '?',
            'App\\Controller\\SuiviController:edit' => '?',
            'App\\Controller\\SuiviController:exportPdf' => '?',
            'App\\Controller\\SuiviController:filterByEmergency' => '?',
            'App\\Controller\\SuiviController:getOrganSymptoms' => '?',
            'App\\Controller\\SuiviController:index' => '?',
            'App\\Controller\\SuiviController:searchByEtat' => '?',
            'App\\Controller\\SuiviController:searchByType' => '?',
            'App\\Controller\\SuiviController:sortByDate' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.lRzV.gs'])) {
            return $container->privates['.service_locator.lRzV.gs'];
        }

        return $container->privates['.service_locator.lRzV.gs'] = $instance;
    }
}
