<?php

namespace ContainerXs1qjG4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fg93DDdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fg93DDd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fg93DDd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'suivi' => ['privates', '.errored..service_locator.Fg93DDd.App\\Entity\\Suivi', NULL, 'Cannot autowire service ".service_locator.Fg93DDd": it needs an instance of "App\\Entity\\Suivi" but this type has been excluded in "config/services.yaml".'],
        ], [
            'suivi' => 'App\\Entity\\Suivi',
        ]);
    }
}
