<?php

namespace ContainerAUg7A6v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UuML20fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uuML20f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uuML20f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'suiviRepository' => ['privates', 'App\\Repository\\SuiviRepository', 'getSuiviRepositoryService', true],
        ], [
            'suiviRepository' => 'App\\Repository\\SuiviRepository',
        ]);
    }
}
