<?php

namespace ContainerVVaJx4r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3Jt5a2rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3Jt5a2r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'participation' => ['privates', '.errored..service_locator.3Jt5a2r.App\\Entity\\Participation', NULL, 'Cannot autowire service ".service_locator.3Jt5a2r": it needs an instance of "App\\Entity\\Participation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'emailService' => 'App\\Service\\EmailService',
            'entityManager' => '?',
            'participation' => 'App\\Entity\\Participation',
        ]);

        if (isset($container->privates['.service_locator.3Jt5a2r'])) {
            return $container->privates['.service_locator.3Jt5a2r'];
        }

        return $container->privates['.service_locator.3Jt5a2r'] = $instance;
    }
}
