<?php

namespace ContainerVVaJx4r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__SahYEdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..SahYEd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'guest' => ['privates', '.errored..service_locator..SahYEd.App\\Entity\\Guest', NULL, 'Cannot autowire service ".service_locator..SahYEd": it needs an instance of "App\\Entity\\Guest" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'guest' => 'App\\Entity\\Guest',
        ]);

        if (isset($container->privates['.service_locator..SahYEd'])) {
            return $container->privates['.service_locator..SahYEd'];
        }

        return $container->privates['.service_locator..SahYEd'] = $instance;
    }
}
