<?php

namespace ContainerVVaJx4r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0b2sh7YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0b2sh7Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0b2sh7Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'guestRepository' => ['privates', 'App\\Repository\\GuestRepository', 'getGuestRepositoryService', true],
        ], [
            'guestRepository' => 'App\\Repository\\GuestRepository',
        ]);
    }
}
