<?php

namespace ContainerVVaJx4r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HhCKPbHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HhCKPbH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HhCKPbH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'evenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'httpClient' => ['privates', '.debug.http_client', 'get_Debug_HttpClientService', false],
        ], [
            'evenementRepository' => 'App\\Repository\\EvenementRepository',
            'httpClient' => '?',
        ]);
    }
}
