<?php

namespace ContainerVVaJx4r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WEa3JRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W_ea3JR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'evenement' => ['privates', '.errored..service_locator.W_ea3JR.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.W_ea3JR": it needs an instance of "App\\Entity\\Evenement" but this type has been excluded in "config/services.yaml".'],
            'evenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
        ], [
            'entityManager' => '?',
            'evenement' => 'App\\Entity\\Evenement',
            'evenementRepository' => 'App\\Repository\\EvenementRepository',
        ]);

        if (isset($container->privates['.service_locator.W_ea3JR'])) {
            return $container->privates['.service_locator.W_ea3JR'];
        }

        return $container->privates['.service_locator.W_ea3JR'] = $instance;
    }
}
