<?php

namespace ContainerVVaJx4r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WsDemYSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WsDemYS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\EvenementController::delete' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EvenementController::edit' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EvenementController::filter' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EvenementController::index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EvenementController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EvenementController::show' => ['privates', '.service_locator.td4zu.o', 'get_ServiceLocator_Td4zu_OService', true],
            'App\\Controller\\GuestController::delete' => ['privates', '.service_locator..SahYEd', 'get_ServiceLocator__SahYEdService', true],
            'App\\Controller\\GuestController::edit' => ['privates', '.service_locator..SahYEd', 'get_ServiceLocator__SahYEdService', true],
            'App\\Controller\\GuestController::filter' => ['privates', '.service_locator.0b2sh7Y', 'get_ServiceLocator_0b2sh7YService', true],
            'App\\Controller\\GuestController::index' => ['privates', '.service_locator.0b2sh7Y', 'get_ServiceLocator_0b2sh7YService', true],
            'App\\Controller\\GuestController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\GuestController::show' => ['privates', '.service_locator.DXuwMvl', 'get_ServiceLocator_DXuwMvlService', true],
            'App\\Controller\\PageController::home' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\ParticipationController::cancel' => ['privates', '.service_locator._7hG3Ba', 'get_ServiceLocator_7hG3BaService', true],
            'App\\Controller\\ParticipationController::confirm' => ['privates', '.service_locator.3Jt5a2r', 'get_ServiceLocator_3Jt5a2rService', true],
            'App\\Controller\\ParticipationController::delete' => ['privates', '.service_locator._7hG3Ba', 'get_ServiceLocator_7hG3BaService', true],
            'App\\Controller\\ParticipationController::edit' => ['privates', '.service_locator._7hG3Ba', 'get_ServiceLocator_7hG3BaService', true],
            'App\\Controller\\ParticipationController::filter' => ['privates', '.service_locator.jWlaXqk', 'get_ServiceLocator_JWlaXqkService', true],
            'App\\Controller\\ParticipationController::index' => ['privates', '.service_locator.jWlaXqk', 'get_ServiceLocator_JWlaXqkService', true],
            'App\\Controller\\ParticipationController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ParticipationController::show' => ['privates', '.service_locator.7Fv2XHF', 'get_ServiceLocator_7Fv2XHFService', true],
            'App\\Controller\\PublicEventController::detail' => ['privates', '.service_locator.W_ea3JR', 'get_ServiceLocator_WEa3JRService', true],
            'App\\Controller\\PublicEventController::filterEvents' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\PublicEventController::index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\PublicEventController::recommendEvents' => ['privates', '.service_locator.HhCKPbH', 'get_ServiceLocator_HhCKPbHService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\EvenementController:delete' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EvenementController:edit' => ['privates', '.service_locator.JFCU_Ej', 'get_ServiceLocator_JFCUEjService', true],
            'App\\Controller\\EvenementController:filter' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EvenementController:index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EvenementController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EvenementController:show' => ['privates', '.service_locator.td4zu.o', 'get_ServiceLocator_Td4zu_OService', true],
            'App\\Controller\\GuestController:delete' => ['privates', '.service_locator..SahYEd', 'get_ServiceLocator__SahYEdService', true],
            'App\\Controller\\GuestController:edit' => ['privates', '.service_locator..SahYEd', 'get_ServiceLocator__SahYEdService', true],
            'App\\Controller\\GuestController:filter' => ['privates', '.service_locator.0b2sh7Y', 'get_ServiceLocator_0b2sh7YService', true],
            'App\\Controller\\GuestController:index' => ['privates', '.service_locator.0b2sh7Y', 'get_ServiceLocator_0b2sh7YService', true],
            'App\\Controller\\GuestController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\GuestController:show' => ['privates', '.service_locator.DXuwMvl', 'get_ServiceLocator_DXuwMvlService', true],
            'App\\Controller\\PageController:home' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\ParticipationController:cancel' => ['privates', '.service_locator._7hG3Ba', 'get_ServiceLocator_7hG3BaService', true],
            'App\\Controller\\ParticipationController:confirm' => ['privates', '.service_locator.3Jt5a2r', 'get_ServiceLocator_3Jt5a2rService', true],
            'App\\Controller\\ParticipationController:delete' => ['privates', '.service_locator._7hG3Ba', 'get_ServiceLocator_7hG3BaService', true],
            'App\\Controller\\ParticipationController:edit' => ['privates', '.service_locator._7hG3Ba', 'get_ServiceLocator_7hG3BaService', true],
            'App\\Controller\\ParticipationController:filter' => ['privates', '.service_locator.jWlaXqk', 'get_ServiceLocator_JWlaXqkService', true],
            'App\\Controller\\ParticipationController:index' => ['privates', '.service_locator.jWlaXqk', 'get_ServiceLocator_JWlaXqkService', true],
            'App\\Controller\\ParticipationController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ParticipationController:show' => ['privates', '.service_locator.7Fv2XHF', 'get_ServiceLocator_7Fv2XHFService', true],
            'App\\Controller\\PublicEventController:detail' => ['privates', '.service_locator.W_ea3JR', 'get_ServiceLocator_WEa3JRService', true],
            'App\\Controller\\PublicEventController:filterEvents' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\PublicEventController:index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\PublicEventController:recommendEvents' => ['privates', '.service_locator.HhCKPbH', 'get_ServiceLocator_HhCKPbHService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\EvenementController::delete' => '?',
            'App\\Controller\\EvenementController::edit' => '?',
            'App\\Controller\\EvenementController::filter' => '?',
            'App\\Controller\\EvenementController::index' => '?',
            'App\\Controller\\EvenementController::new' => '?',
            'App\\Controller\\EvenementController::show' => '?',
            'App\\Controller\\GuestController::delete' => '?',
            'App\\Controller\\GuestController::edit' => '?',
            'App\\Controller\\GuestController::filter' => '?',
            'App\\Controller\\GuestController::index' => '?',
            'App\\Controller\\GuestController::new' => '?',
            'App\\Controller\\GuestController::show' => '?',
            'App\\Controller\\PageController::home' => '?',
            'App\\Controller\\ParticipationController::cancel' => '?',
            'App\\Controller\\ParticipationController::confirm' => '?',
            'App\\Controller\\ParticipationController::delete' => '?',
            'App\\Controller\\ParticipationController::edit' => '?',
            'App\\Controller\\ParticipationController::filter' => '?',
            'App\\Controller\\ParticipationController::index' => '?',
            'App\\Controller\\ParticipationController::new' => '?',
            'App\\Controller\\ParticipationController::show' => '?',
            'App\\Controller\\PublicEventController::detail' => '?',
            'App\\Controller\\PublicEventController::filterEvents' => '?',
            'App\\Controller\\PublicEventController::index' => '?',
            'App\\Controller\\PublicEventController::recommendEvents' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EvenementController:delete' => '?',
            'App\\Controller\\EvenementController:edit' => '?',
            'App\\Controller\\EvenementController:filter' => '?',
            'App\\Controller\\EvenementController:index' => '?',
            'App\\Controller\\EvenementController:new' => '?',
            'App\\Controller\\EvenementController:show' => '?',
            'App\\Controller\\GuestController:delete' => '?',
            'App\\Controller\\GuestController:edit' => '?',
            'App\\Controller\\GuestController:filter' => '?',
            'App\\Controller\\GuestController:index' => '?',
            'App\\Controller\\GuestController:new' => '?',
            'App\\Controller\\GuestController:show' => '?',
            'App\\Controller\\PageController:home' => '?',
            'App\\Controller\\ParticipationController:cancel' => '?',
            'App\\Controller\\ParticipationController:confirm' => '?',
            'App\\Controller\\ParticipationController:delete' => '?',
            'App\\Controller\\ParticipationController:edit' => '?',
            'App\\Controller\\ParticipationController:filter' => '?',
            'App\\Controller\\ParticipationController:index' => '?',
            'App\\Controller\\ParticipationController:new' => '?',
            'App\\Controller\\ParticipationController:show' => '?',
            'App\\Controller\\PublicEventController:detail' => '?',
            'App\\Controller\\PublicEventController:filterEvents' => '?',
            'App\\Controller\\PublicEventController:index' => '?',
            'App\\Controller\\PublicEventController:recommendEvents' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.WsDemYS'])) {
            return $container->privates['.service_locator.WsDemYS'];
        }

        return $container->privates['.service_locator.WsDemYS'] = $instance;
    }
}
