<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTjV4NoX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTjV4NoX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTjV4NoX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTjV4NoX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTjV4NoX\App_KernelDevDebugContainer([
    'container.build_hash' => 'TjV4NoX',
    'container.build_id' => '1e0a7d33',
    'container.build_time' => 1772183504,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTjV4NoX');
