<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQgV2AqH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQgV2AqH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQgV2AqH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQgV2AqH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQgV2AqH\App_KernelDevDebugContainer([
    'container.build_hash' => 'QgV2AqH',
    'container.build_id' => '616ea18d',
    'container.build_time' => 1771622173,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQgV2AqH');
