<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEUeFEUx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEUeFEUx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEUeFEUx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEUeFEUx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEUeFEUx\App_KernelDevDebugContainer([
    'container.build_hash' => 'EUeFEUx',
    'container.build_id' => '5c9d77e1',
    'container.build_time' => 1770935643,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEUeFEUx');
