<?php

namespace ContainerTjV4NoX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_APN3E1UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.APN3E1U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'consultation' => ['privates', '.errored..service_locator.APN3E1U.App\\Entity\\Consultation', NULL, 'Cannot autowire service ".service_locator.APN3E1U": it needs an instance of "App\\Entity\\Consultation" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'suiviRepository' => ['privates', 'App\\Repository\\SuiviRepository', 'getSuiviRepositoryService', true],
        ], [
            'consultation' => 'App\\Entity\\Consultation',
            'em' => '?',
            'suiviRepository' => 'App\\Repository\\SuiviRepository',
        ]);

        if (isset($container->privates['.service_locator.APN3E1U'])) {
            return $container->privates['.service_locator.APN3E1U'];
        }

        return $container->privates['.service_locator.APN3E1U'] = $instance;
    }
}
