<?php

namespace ContainerTjV4NoX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F9TuKpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f9Tu_kp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'twilioService' => ['privates', 'App\\Service\\TwilioNotificationService', 'getTwilioNotificationServiceService', true],
        ], [
            'em' => '?',
            'twilioService' => 'App\\Service\\TwilioNotificationService',
        ]);

        if (isset($container->privates['.service_locator.f9Tu_kp'])) {
            return $container->privates['.service_locator.f9Tu_kp'];
        }

        return $container->privates['.service_locator.f9Tu_kp'] = $instance;
    }
}
