<?php

namespace ContainerTjV4NoX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwilioNotificationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TwilioNotificationService' shared autowired service.
     *
     * @return \App\Service\TwilioNotificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TwilioNotificationService.php';

        return $container->privates['App\\Service\\TwilioNotificationService'] = new \App\Service\TwilioNotificationService($container->getEnv('default::TWILIO_ACCOUNT_SID'), $container->getEnv('default::TWILIO_AUTH_TOKEN'), $container->getEnv('default::TWILIO_PHONE_NUMBER'), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
