<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ZiptagInfo extends \App\Entity\ZiptagInfo implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'batteryLevel' => [parent::class, 'batteryLevel', null, 16],
        "\0".parent::class."\0".'bodyTemperature' => [parent::class, 'bodyTemperature', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'heartRate' => [parent::class, 'heartRate', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null, 16],
        "\0".parent::class."\0".'message' => [parent::class, 'message', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'ziptag' => [parent::class, 'ziptag', null, 16],
        'batteryLevel' => [parent::class, 'batteryLevel', null, 16],
        'bodyTemperature' => [parent::class, 'bodyTemperature', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'heartRate' => [parent::class, 'heartRate', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'location' => [parent::class, 'location', null, 16],
        'message' => [parent::class, 'message', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'ziptag' => [parent::class, 'ziptag', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
