<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Guest extends \App\Entity\Guest implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'bio' => [parent::class, 'bio', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'evenement' => [parent::class, 'evenement', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'organisation' => [parent::class, 'organisation', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        'bio' => [parent::class, 'bio', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'evenement' => [parent::class, 'evenement', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'organisation' => [parent::class, 'organisation', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'role' => [parent::class, 'role', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
