<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ObservationStation extends \App\Entity\ObservationStation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'alerts' => [parent::class, 'alerts', null, 16],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'localisation' => [parent::class, 'localisation', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'zone' => [parent::class, 'zone', null, 16],
        'alerts' => [parent::class, 'alerts', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'localisation' => [parent::class, 'localisation', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'zone' => [parent::class, 'zone', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
