<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ziptag extends \App\Entity\Ziptag implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dog' => [parent::class, 'dog', null, 16],
        "\0".parent::class."\0".'firmwareVersion' => [parent::class, 'firmwareVersion', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'infos' => [parent::class, 'infos', null, 16],
        "\0".parent::class."\0".'model' => [parent::class, 'model', null, 16],
        "\0".parent::class."\0".'serialNumber' => [parent::class, 'serialNumber', null, 16],
        'dog' => [parent::class, 'dog', null, 16],
        'firmwareVersion' => [parent::class, 'firmwareVersion', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'infos' => [parent::class, 'infos', null, 16],
        'model' => [parent::class, 'model', null, 16],
        'serialNumber' => [parent::class, 'serialNumber', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
