<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dogs extends \App\Entity\Dogs implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adoption_status' => [parent::class, 'adoption_status', null, 16],
        "\0".parent::class."\0".'age' => [parent::class, 'age', null, 16],
        "\0".parent::class."\0".'arrival_date' => [parent::class, 'arrival_date', null, 16],
        "\0".parent::class."\0".'breed' => [parent::class, 'breed', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'friendly_with_cats' => [parent::class, 'friendly_with_cats', null, 16],
        "\0".parent::class."\0".'friendly_with_dogs' => [parent::class, 'friendly_with_dogs', null, 16],
        "\0".parent::class."\0".'friendly_with_kids' => [parent::class, 'friendly_with_kids', null, 16],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null, 16],
        "\0".parent::class."\0".'health_status' => [parent::class, 'health_status', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'microchip_number' => [parent::class, 'microchip_number', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'size' => [parent::class, 'size', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        "\0".parent::class."\0".'vaccinated' => [parent::class, 'vaccinated', null, 16],
        "\0".parent::class."\0".'weight' => [parent::class, 'weight', null, 16],
        "\0".parent::class."\0".'ziptag' => [parent::class, 'ziptag', null, 16],
        'adoption_status' => [parent::class, 'adoption_status', null, 16],
        'age' => [parent::class, 'age', null, 16],
        'arrival_date' => [parent::class, 'arrival_date', null, 16],
        'breed' => [parent::class, 'breed', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'friendly_with_cats' => [parent::class, 'friendly_with_cats', null, 16],
        'friendly_with_dogs' => [parent::class, 'friendly_with_dogs', null, 16],
        'friendly_with_kids' => [parent::class, 'friendly_with_kids', null, 16],
        'gender' => [parent::class, 'gender', null, 16],
        'health_status' => [parent::class, 'health_status', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'microchip_number' => [parent::class, 'microchip_number', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'size' => [parent::class, 'size', null, 16],
        'user' => [parent::class, 'user', null, 16],
        'vaccinated' => [parent::class, 'vaccinated', null, 16],
        'weight' => [parent::class, 'weight', null, 16],
        'ziptag' => [parent::class, 'ziptag', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
